### PR TITLE
chore: generate github action for api docs deployment

### LINKED ISSUE #2: Release API documentation using GitHub Actions
As the title suggests...

### PR DESCRIPTION
**Pull request by alioguzhan**
Closes #2

### CODE REVIEW

**Review by vst — APPROVED** [review]
:+1:

I suppose that this will generate API docs only when we make a new release eventually.

**Comment by alioguzhan** [comment]
Hmm. This will deploy docs on both PR and Push. May be i should change it to only Push? @vst

**Comment by vst** [comment]
> Hmm. This will deploy docs on both PR and Push. May be i should change it to only Push? @vst

Yes. I think when pushed only to main, indeed. We want that the published API and latest NPM release match.

**Comment by alioguzhan** [comment]
Done.

**Review by vst — APPROVED** [review]
All is well, then...

**Pull request merged**
